### ISSUE TITLE
JSPM edge case?

### ISSUE THREAD

**Issue by buddyp450** [nolanlawson/package-json-versionify#7]
I'm currently using JSPM and use the json loader to import like:

`import pkg from './package.json!'`

and I'm seeing the entire structure.

**Comment by fanatid** [comment]
Probably this is problem https://github.com/fanatid/browserify-package-json/blob/v1.0.1/index.js#L4
We can pass regexp via options.

**Comment by nolanlawson** [comment]
Thanks for filing this issue. Sorry, but this repo only intends to support browserify, not JSPM.
